server:
  port: 80
  session:
    timeout: 1800
  tomcat:
    max-threads: 3000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://napsterlong.mysql.rds.aliyuncs.com:3306
    name: test
    username: root
    password: root
  http:
    multipart:
      enabled: true
logging:
  config: classpath:config/log4j2-prod.xml

rootPath: /resources



